### PR TITLE
Consistent variable names

### PR DESCRIPTION
**Pull request by cam-schultz**
## Why this should be merged
Fixes https://github.com/ava-labs/teleporter/issues/189

## How this works
Renames vars

## How this was tested
CI

## How is this documented
N/A

### CODE REVIEW

**Comment by cam-schultz** [comment]
The [vulnerability](https://github.com/ava-labs/avalanche-cli/pull/1344) reported by Snyk is coming from the `avalanche-cli` installation in the testing container. It's [fixed](https://github.com/ava-labs/avalanche-cli/pull/1344) in the repo, but we'll have to wait for the next `avalanche-cli` release for this to go away. Since this container is used for testing only, this is not a blocker.

**Review by geoff-vball — DISMISSED** [review]

**Comment by michaelkaplan13** [comment]
There are a few more places that we should update:
image

**Comment by michaelkaplan13** [comment]
We should also rename `DEFAULT_ORIGIN_BLOCKCHAIN_ID` to `DEFAULT_SOURCE_BLOCKCHAIN_ID`.

**Comment by michaelkaplan13** [comment]
Looks like `originChainID` is used in a few places still.

**Comment by cam-schultz** [comment]
> Looks like `originChainID` is used in a few places still.

Whoops, fixed now. I also updated `destinationChainID` -> `destinationBlockchainID`

**Comment by michaelkaplan13** [comment]
Final few nits. In the three cases below, can we update to `BlockchainID` (either adding the "Block" or lower-casing the C in "Chain")

image

**Comment by cam-schultz** [comment]
> Final few nits. In the three cases below, can we update to `BlockchainID` (either adding the "Block" or lower-casing the C in "Chain")

Sure thing. Also renamed `getBlockChainId.py` -> `getBlockchainId.py`

**Review by michaelkaplan13 — APPROVED** [review]
🚀

**Review by minghinmatthewlam — APPROVED** [review]
LGTM

**Pull request merged**
