### PR TITLE
Rename retryReceipts to sendReceipts

### PR DESCRIPTION
**Pull request by minghinmatthewlam**
## Why this should be merged
Originally the contract had function `retryReceipt` that then changed to `retryReceipts`, but this function is sending a new noop Teleporter message, so `sendReceipts` more appropriately describes the functionality.

## How is this documented
updated existing documentation for retryReceipts

### CODE REVIEW

**Comment by michaelkaplan13** [comment]
👍 definitely agree on the concept, now I'm just thinking if `sendReceipts` make it seem as though you need to call it for receipts to be sent...

What do you think of `sendCustomReceipts`? Open to other ideas as well

**Comment by minghinmatthewlam** [comment]
> 👍 definitely agree on the concept, now I'm just thinking if `sendReceipts` make it seem as though you need to call it for receipts to be sent...
> 
> What do you think of `sendCustomReceipts`? Open to other ideas as well

good point, definitely should stay away from just `sendReceipts` then. I'm good with `sendCustomReceipts`, will on it a bit, but if nothing else pops up will change accordingly

**Review by cam-schultz — DISMISSED** [review]

**Review by geoff-vball — DISMISSED** [review]

**Review by bernard-avalabs — COMMENTED** [review]
Maybe sendSpecifiedReceipts instead of sendCustomReceipts? Or perhaps sendSelectedReceipts?

It is hard to guess what sendCustomReceipts is used for without reading the comments.

**Comment by michaelkaplan13** [comment]
> Maybe sendSpecifiedReceipts instead of sendCustomReceipts? Or perhaps sendSelectedReceipts?
> 
> It is hard to guess what sendCustomReceipts is used for without reading the comments.

I agree `sendSpecifiedReceipts` is better than `sendCustomReceipts`. Thanks for the suggestion

**Review by michaelkaplan13 — APPROVED** [review]
LGTM!

**Review by cam-schultz — APPROVED** [review]

**Pull request merged**
