### PR TITLE
subnet-evm v0.5.9

### PR DESCRIPTION
**Pull request by cam-schultz**
## Why this should be merged
Updates to subnet-evm v0.5.9 and avalanchego v1.10.15. Fixes https://github.com/ava-labs/teleporter/issues/122

## How this was tested
CI

### CODE REVIEW

**Review by geoff-vball — DISMISSED** [review]
Needs some conflicts resolved, but otherwise lgtm

**Review by bernard-avalabs — APPROVED** [review]
LGTM

**Review by michaelkaplan13 — APPROVED** [review]

**Review by minghinmatthewlam — APPROVED** [review]
LGTM

**Review by michaelkaplan13 — APPROVED** [review]

**Review by gwen917 — APPROVED** [review]
LGTM

**Pull request merged**
