### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by meaghanfitzgerald**
:)

### CODE REVIEW

**Review by minghinmatthewlam — DISMISSED** [review]

**Review by cam-schultz — DISMISSED** [review]
LGTM. Confirmed that the Github view is unchanged. Is this for easier inclusion in the public docs website?

**Comment by meaghanfitzgerald** [comment]
@cam-schultz Yes def. for image elements, `src` should point to a relative element (appended with something like `./` or `../../../`) with the `?raw=true`.  Otherwise the page gets rendered without the image.

**Comment by meaghanfitzgerald** [comment]
(apologies in advance for the future PR's i raise with super trivial changes 😁 )

**Review by michaelkaplan13 — DISMISSED** [review]

**Review by geoff-vball — APPROVED** [review]
🙏

**Review by michaelkaplan13 — APPROVED** [review]

**Comment by meaghanfitzgerald** [comment]
Kk, that should be it for now. Once these changes are merged to master, you will see them reflected here: https://teleporter-awm.avalanche-docs.pages.dev/build/cross-chain/teleporter/overview

Here's the PR to add these to the docs: https://github.com/ava-labs/avalanche-docs/pull/1554

**Pull request merged**
